WORLD_TECHNIQUES = {
    "疾风步":       {"type": "辅助", "grade": "黄级中品", "stat_bonus": {"escape_rate": 8}, "desc": "轻功入门心法，身法灵动，逃跑成功率小幅提升。"},
    "铁砂掌":       {"type": "攻击", "grade": "黄级中品", "stat_bonus": {"physique": 1}, "desc": "以掌力淬炼体魄，近身攻击力提升。"},
    "聚气诀":       {"type": "修炼", "grade": "黄级中品", "stat_bonus": {"cultivation_speed": 0.08}, "desc": "基础聚气心法，修炼速度略有提升。"},
    "望气术":       {"type": "辅助", "grade": "黄级中品", "stat_bonus": {"soul": 1}, "desc": "可感知周围灵气波动，神识小幅提升。"},
    "固元功":       {"type": "防御", "grade": "黄级中品", "stat_bonus": {"bone": 1}, "desc": "稳固根基，根骨小幅强化。"},

    "穿云剑法":     {"type": "攻击", "grade": "黄级上品", "stat_bonus": {"comprehension": 1, "cultivation_speed": 0.05}, "desc": "江湖流传的剑法，悟性越高威力越强。"},
    "金钟罩":       {"type": "防御", "grade": "黄级上品", "stat_bonus": {"physique": 2}, "desc": "以气护体，体魄大幅强化。"},
    "缩地术":       {"type": "辅助", "grade": "黄级上品", "stat_bonus": {"escape_rate": 12}, "desc": "瞬间移位之术，逃跑成功率显著提升。"},
    "吞星功":       {"type": "修炼", "grade": "黄级上品", "stat_bonus": {"cultivation_speed": 0.12, "bone": 1}, "desc": "吞纳星辰灵气，修炼速度与根骨同步提升。"},
    "神行百变":     {"type": "辅助", "grade": "黄级上品", "stat_bonus": {"escape_rate": 15, "fortune": 1}, "desc": "变化莫测的身法，机缘与逃跑成功率均有提升。"},

    "破军刀法":     {"type": "攻击", "grade": "玄级下品", "stat_bonus": {"physique": 2, "bone": 1}, "desc": "古战场遗留的刀法，杀伐之气凝聚，体魄与根骨强化。"},
    "玄天心法":     {"type": "修炼", "grade": "玄级下品", "stat_bonus": {"cultivation_speed": 0.25, "soul": 1}, "desc": "玄门正宗心法，修炼速度与神识同步提升。"},
    "千机变":       {"type": "辅助", "grade": "玄级下品", "stat_bonus": {"fortune": 2, "escape_rate": 10}, "desc": "机缘心法，感知天地变化，机缘与逃跑成功率提升。"},
    "罡气护体":     {"type": "防御", "grade": "玄级下品", "stat_bonus": {"physique": 2, "bone": 2}, "desc": "以罡气形成护盾，体魄与根骨大幅强化。"},

    "九转玄功":     {"type": "修炼", "grade": "玄级中品", "stat_bonus": {"cultivation_speed": 0.35, "comprehension": 2}, "desc": "传说中的九转心法，修炼速度与悟性大幅提升。"},
    "天罗地网步":   {"type": "辅助", "grade": "玄级中品", "stat_bonus": {"escape_rate": 20, "soul": 2}, "desc": "极致的身法与神识配合，逃跑成功率与神识大幅提升。"},
    "万象归一":     {"type": "攻击", "grade": "玄级中品", "stat_bonus": {"comprehension": 2, "soul": 2}, "desc": "融合万象之力，悟性与神识同步强化。"},

    "混元一气功":   {"type": "修炼", "grade": "玄级上品", "stat_bonus": {"cultivation_speed": 0.45, "comprehension": 2, "physique": 1}, "desc": "上古传承，混元之气贯通全身，修炼速度与多项属性提升。"},
    "逍遥游":       {"type": "辅助", "grade": "玄级上品", "stat_bonus": {"escape_rate": 25, "fortune": 2, "soul": 1}, "desc": "传说中的逍遥身法，如风如影，逃跑成功率极高。"},

    "太乙延寿功":   {"type": "修炼", "grade": "黄级上品", "stat_bonus": {"lifespan_bonus": 8, "bone": 1}, "desc": "专注延寿之道，以根骨为基，缓缓延长天年。"},
    "驻颜术":       {"type": "辅助", "grade": "黄级上品", "stat_bonus": {"lifespan_bonus": 6, "fortune": 1}, "desc": "以灵气滋养肉身，岁月难侵，寿元小幅延长。"},
    "长生诀":       {"type": "修炼", "grade": "玄级下品", "stat_bonus": {"lifespan_bonus": 15, "soul": 1}, "desc": "上古长生功法残篇，修炼后寿元上限显著提升。"},

    "阴阳调和诀":   {"type": "特殊", "grade": "黄级上品", "stat_bonus": {"fortune": 2, "soul": 1}, "desc": "调和阴阳之气，双修时感悟更深，机缘与神识同步提升。"},
    "采灵诀":       {"type": "修炼", "grade": "黄级中品", "stat_bonus": {"cultivation_speed": 0.06, "fortune": 1}, "desc": "感应天地灵气流动，修炼效率与机缘略有提升。"},
    "五行感应":     {"type": "辅助", "grade": "黄级上品", "stat_bonus": {"comprehension": 1, "fortune": 1, "soul": 1}, "desc": "感应五行之力，悟性、机缘、神识均有小幅提升。"},

    "霸体诀":       {"type": "防御", "grade": "黄级上品", "stat_bonus": {"physique": 2, "bone": 1}, "desc": "淬炼肉身至极，体魄与根骨同步强化，防御力大增。"},
    "玄骨功":       {"type": "防御", "grade": "玄级下品", "stat_bonus": {"bone": 3, "physique": 1}, "desc": "专修根骨的功法，骨骼坚如玄铁，突破成功率隐性提升。"},
    "神魂锻体":     {"type": "防御", "grade": "玄级中品", "stat_bonus": {"bone": 2, "soul": 2, "physique": 1}, "desc": "以神魂之力淬炼肉身，三项属性同步强化，防御全面。"},

    "缩骨幻形术":   {"type": "辅助", "grade": "玄级下品", "stat_bonus": {"escape_rate": 18, "soul": 1}, "desc": "改变体型气息的秘术，神识越强越难被追踪，逃跑成功率大幅提升。"},
    "天命感知":     {"type": "辅助", "grade": "玄级中品", "stat_bonus": {"fortune": 3, "comprehension": 1}, "desc": "感知天命流转，机缘大幅提升，偶尔能提前感应到危险。"},
    "破妄神通":     {"type": "攻击", "grade": "玄级下品", "stat_bonus": {"comprehension": 2, "bone": 1}, "desc": "以悟性破除一切虚妄，攻击时无视部分防御，悟性与根骨强化。"},
    "噬元大法":     {"type": "攻击", "grade": "玄级中品", "stat_bonus": {"physique": 2, "soul": 2}, "desc": "吞噬对手元气为己用，体魄与神识同步强化，战斗中越打越强。"},
    "归元心法":     {"type": "修炼", "grade": "玄级下品", "stat_bonus": {"cultivation_speed": 0.20, "bone": 1, "soul": 1}, "desc": "引导元气归于本源，修炼速度、根骨、神识三项同步提升。"},
    "万古长青功":   {"type": "修炼", "grade": "玄级上品", "stat_bonus": {"lifespan_bonus": 25, "cultivation_speed": 0.20, "bone": 2}, "desc": "传说中长生不老的功法残卷，寿元延长效果冠绝同阶，修炼速度与根骨亦有提升。"},

    "玄冥指":       {"type": "攻击", "grade": "黄级上品", "stat_bonus": {"soul": 1, "bone": 1}, "desc": "以神识驱动指力，攻击时带有神识侵蚀，神识与根骨同步强化。"},
    "天罡护盾":     {"type": "防御", "grade": "黄级上品", "stat_bonus": {"physique": 1, "soul": 1}, "desc": "以天罡之气凝聚护盾，体魄与神识均有提升。"},
    "悟道心经":     {"type": "修炼", "grade": "黄级上品", "stat_bonus": {"comprehension": 2, "cultivation_speed": 0.08}, "desc": "专注感悟天道的心经，悟性大幅提升，修炼速度略有加快。"},
    "鬼步":         {"type": "辅助", "grade": "黄级上品", "stat_bonus": {"escape_rate": 10, "soul": 1}, "desc": "模仿鬼魂游走的步法，神出鬼没，逃跑成功率与神识提升。"},
    "铸骨功":       {"type": "防御", "grade": "黄级中品", "stat_bonus": {"bone": 1, "physique": 1}, "desc": "以灵气淬炼骨骼与肉身，根骨与体魄同步小幅强化。"},
    "烈阳拳":       {"type": "攻击", "grade": "黄级中品", "stat_bonus": {"physique": 1}, "desc": "以烈阳之意淬炼拳劲，近身攻击时体魄略有强化。"},
    "青木身法":     {"type": "辅助", "grade": "黄级中品", "stat_bonus": {"escape_rate": 8, "physique": 1}, "desc": "模仿青木摇曳之姿的身法，步伐灵动，逃跑成功率与体魄略有提升。"},
    "静心吐纳法":   {"type": "修炼", "grade": "黄级中品", "stat_bonus": {"cultivation_speed": 0.07, "soul": 1}, "desc": "以吐纳稳心神，修炼速度略增，神识同步小幅提升。"},
    "金石锻骨诀":   {"type": "防御", "grade": "黄级中品", "stat_bonus": {"bone": 1, "physique": 1}, "desc": "借金石之意淬炼筋骨，根骨与体魄同步略有强化。"},
    "流云身法":     {"type": "辅助", "grade": "黄级上品", "stat_bonus": {"escape_rate": 18, "fortune": 1}, "desc": "如流云般飘忽的身法，行迹难测，逃跑成功率与机缘均有提升。"},
    "星辰观想":     {"type": "修炼", "grade": "黄级上品", "stat_bonus": {"comprehension": 2, "soul": 1}, "desc": "夜观星辰推演轨迹，悟性大幅提升，神识亦有所精进。"},
    "绛霞护体":     {"type": "防御", "grade": "黄级上品", "stat_bonus": {"physique": 2, "soul": 1}, "desc": "以绛霞灵光护体，体魄与神识同时得到强化。"},
    "血煞刀诀":     {"type": "攻击", "grade": "黄级上品", "stat_bonus": {"physique": 2, "bone": 1}, "desc": "借血煞之意凝于刀锋，出刀时体魄与根骨皆有所增益。"},
    "龙象镇狱功":   {"type": "防御", "grade": "玄级下品", "stat_bonus": {"physique": 3, "bone": 2}, "desc": "以龙象之力镇压狱火，体魄与根骨大幅强化，防御惊人。"},
    "太阴养神诀":   {"type": "修炼", "grade": "玄级下品", "stat_bonus": {"soul": 2, "lifespan_bonus": 10}, "desc": "借太阴之力温养神魂，神识与寿元上限同步提升。"},
    "五行轮转诀":   {"type": "修炼", "grade": "玄级下品", "stat_bonus": {"cultivation_speed": 0.28, "comprehension": 1, "bone": 1}, "desc": "以五行轮转之理运转灵气，修炼速度与悟性、根骨均有提升。"},
    "苍穹剑意":     {"type": "攻击", "grade": "玄级下品", "stat_bonus": {"comprehension": 2, "soul": 1}, "desc": "仰观苍穹所悟剑意，出剑时悟性与神识皆有加持。"},
    "影遁术":       {"type": "辅助", "grade": "玄级下品", "stat_bonus": {"escape_rate": 28, "soul": 2}, "desc": "融身于阴影之间的遁术，逃跑成功率极高，神识同步强化。"},
    "日月同辉功":   {"type": "修炼", "grade": "玄级中品", "stat_bonus": {"cultivation_speed": 0.38, "soul": 2, "comprehension": 1}, "desc": "同时调动日阳与月阴之力修炼，修炼速度、神识与悟性皆有显著提升。"},
    "镇狱魔体":     {"type": "防御", "grade": "玄级中品", "stat_bonus": {"physique": 3, "bone": 2, "soul": 1}, "desc": "以狱火与魔气淬炼肉身，体魄、根骨与神识全方位强化。"},
    "玄光御剑诀":   {"type": "攻击", "grade": "玄级中品", "stat_bonus": {"comprehension": 2, "cultivation_speed": 0.20, "soul": 1}, "desc": "以玄光御剑，剑随心走，悟性与神识增强的同时修炼速度亦有提升。"},
    "虚空挪移":     {"type": "辅助", "grade": "玄级中品", "stat_bonus": {"escape_rate": 30, "soul": 2, "fortune": 2}, "desc": "借虚空之力挪移身形，逃跑成功率、神识与机缘大幅提升。"},
    "太上忘情道":   {"type": "修炼", "grade": "玄级上品", "stat_bonus": {"comprehension": 3, "soul": 2, "cultivation_speed": 0.30}, "desc": "以忘情证道，斩去杂念，悟性与神识大幅提升，修炼速度亦明显加快。"},
    "万劫不灭体":   {"type": "防御", "grade": "玄级上品", "stat_bonus": {"physique": 3, "bone": 3, "lifespan_bonus": 20}, "desc": "以万劫之难淬炼肉身与骨骼，体魄、根骨与寿元上限全面强化。"},
    "星河洗髓经":   {"type": "修炼", "grade": "玄级上品", "stat_bonus": {"bone": 2, "soul": 2, "cultivation_speed": 0.35}, "desc": "以星河之力洗涤经脉与神魂，根骨、神识与修炼速度皆有巨大提升。"},
    "碎石拳":       {"type": "攻击", "grade": "黄级中品", "stat_bonus": {"physique": 1}, "desc": "以碎石之劲淬炼拳骨，近身出拳时体魄略有强化。"},
    "云梯步":       {"type": "辅助", "grade": "黄级中品", "stat_bonus": {"escape_rate": 7}, "desc": "步法如登云梯，起落之间身法略有提升，逃跑成功率小幅增加。"},
    "小周天功":     {"type": "修炼", "grade": "黄级中品", "stat_bonus": {"cultivation_speed": 0.06, "bone": 1}, "desc": "运行小周天以疏通经脉，修炼速度与根骨皆有小幅提升。"},
    "养气诀":       {"type": "修炼", "grade": "黄级中品", "stat_bonus": {"cultivation_speed": 0.05, "lifespan_bonus": 3}, "desc": "调息养气的基础功法，修炼速度略增，寿元上限小幅提升。"},
    "护心诀":       {"type": "防御", "grade": "黄级中品", "stat_bonus": {"physique": 1, "bone": 1}, "desc": "以灵气护住心脉，体魄与根骨略有强化。"},
    "凝神术":       {"type": "辅助", "grade": "黄级中品", "stat_bonus": {"soul": 1, "comprehension": 1}, "desc": "收摄心神的入门法门，神识与悟性均有小幅提升。"},
    "引雷指":       {"type": "攻击", "grade": "黄级中品", "stat_bonus": {"soul": 1}, "desc": "以指引雷之意，出指时神识略有增强，附带丝丝雷意。"},
    "回春功":       {"type": "修炼", "grade": "黄级中品", "stat_bonus": {"cultivation_speed": 0.04, "lifespan_bonus": 4}, "desc": "以木春之意温养躯体，修炼略有增益，寿元上限小幅提升。"},
    "步罡踏斗":     {"type": "辅助", "grade": "黄级中品", "stat_bonus": {"escape_rate": 9, "fortune": 1}, "desc": "依周天星斗步行的身法，行走之间机缘与逃跑成功率略有提升。"},
    "粗布护体":     {"type": "防御", "grade": "黄级中品", "stat_bonus": {"physique": 1}, "desc": "以粗布缠身淬炼皮肉的民间炼体术，体魄略有强化。"},
    "风雷剑法":     {"type": "攻击", "grade": "黄级上品", "stat_bonus": {"physique": 1, "comprehension": 1}, "desc": "兼具风之迅疾与雷之刚猛的剑法，体魄与悟性皆有提升。"},
    "水月身法":     {"type": "辅助", "grade": "黄级上品", "stat_bonus": {"escape_rate": 16, "soul": 1}, "desc": "如水中明月般虚实难测的身法，逃跑成功率与神识同步提升。"},
    "养元心法":     {"type": "修炼", "grade": "黄级上品", "stat_bonus": {"cultivation_speed": 0.14, "lifespan_bonus": 6}, "desc": "专注调养元气的心法，修炼速度与寿元上限均有提升。"},
    "灵木护体":     {"type": "防御", "grade": "黄级上品", "stat_bonus": {"physique": 1, "bone": 1, "soul": 1}, "desc": "借灵木之力护体，体魄、根骨与神识皆有小幅强化。"},
    "八门遁甲":     {"type": "辅助", "grade": "黄级上品", "stat_bonus": {"escape_rate": 20, "fortune": 1}, "desc": "以八门遁甲之术变化方位，逃跑成功率与机缘大幅提升。"},
    "清心寂灭功":   {"type": "修炼", "grade": "黄级上品", "stat_bonus": {"comprehension": 2, "soul": 1}, "desc": "以寂灭之心观想自我，悟性大幅提升，神识亦有所精进。"},
    "血脉淬体诀":   {"type": "防御", "grade": "黄级上品", "stat_bonus": {"physique": 2, "bone": 1}, "desc": "以自身血脉为引淬炼肉身，体魄与根骨均有显著强化。"},
    "百战刀诀":     {"type": "攻击", "grade": "黄级上品", "stat_bonus": {"physique": 2}, "desc": "从百战中淬炼出的刀法，体魄在战斗中得到明显强化。"},
    "玄罡步":       {"type": "辅助", "grade": "黄级上品", "stat_bonus": {"escape_rate": 18, "soul": 1}, "desc": "踏玄罡而行的身法，逃跑成功率与神识皆有提升。"},
    "地煞护身":     {"type": "防御", "grade": "黄级上品", "stat_bonus": {"physique": 2, "bone": 1}, "desc": "引地煞之气护身，体魄与根骨同步强化。"},
    "混元战体":     {"type": "防御", "grade": "玄级下品", "stat_bonus": {"physique": 3, "bone": 1}, "desc": "以混元之力锻造战体，体魄大幅提升，根骨略有加强。"},
    "幽冥搜魂":     {"type": "攻击", "grade": "玄级下品", "stat_bonus": {"soul": 2, "comprehension": 1}, "desc": "以幽冥之力搜寻对手神魂，神识与悟性同步增强。"},
    "雷光遁":       {"type": "辅助", "grade": "玄级下品", "stat_bonus": {"escape_rate": 26, "soul": 2}, "desc": "化身雷光瞬间远遁，逃跑成功率极高，神识亦得到强化。"},
    "紫霄真诀":     {"type": "修炼", "grade": "玄级下品", "stat_bonus": {"cultivation_speed": 0.26, "soul": 1, "comprehension": 1}, "desc": "以紫霄之意导引灵气，修炼速度、神识与悟性皆有提升。"},
    "龙吟剑诀":     {"type": "攻击", "grade": "玄级下品", "stat_bonus": {"physique": 2, "comprehension": 2}, "desc": "仿龙吟之势出剑，体魄与悟性同步强化。"},
    "太虚步":       {"type": "辅助", "grade": "玄级中品", "stat_bonus": {"escape_rate": 32, "soul": 2, "fortune": 1}, "desc": "行走太虚之间的身法，逃跑成功率、神识与机缘大幅提升。"},
    "九霄雷体":     {"type": "防御", "grade": "玄级中品", "stat_bonus": {"physique": 3, "soul": 2}, "desc": "以九霄雷意淬炼肉身，体魄与神识得到显著强化。"},
    "玄黄一气经":   {"type": "修炼", "grade": "玄级中品", "stat_bonus": {"cultivation_speed": 0.40, "bone": 1, "comprehension": 2}, "desc": "调动玄黄一气修炼，修炼速度、根骨与悟性均有明显提升。"},
    "寂灭魔功":     {"type": "攻击", "grade": "玄级中品", "stat_bonus": {"physique": 3, "soul": 2}, "desc": "以寂灭魔意驱动攻击，体魄与神识在战斗中迅速增强。"},
    "万灵祭炼法":   {"type": "修炼", "grade": "玄级中品", "stat_bonus": {"cultivation_speed": 0.36, "soul": 2, "fortune": 2}, "desc": "借万灵之力祭炼自身，修炼速度、神识与机缘同步提升。"},
    "道心种魔":     {"type": "修炼", "grade": "玄级上品", "stat_bonus": {"comprehension": 3, "soul": 3}, "desc": "以种魔稳固道心，悟性与神识均得到极大强化。"},
    "无相神功":     {"type": "防御", "grade": "玄级上品", "stat_bonus": {"physique": 3, "bone": 1, "soul": 2}, "desc": "身如无相，攻防难测，体魄、根骨与神识全面提升。"},
    "星斗移形":     {"type": "辅助", "grade": "玄级上品", "stat_bonus": {"escape_rate": 35, "soul": 3, "fortune": 2}, "desc": "借星斗之力移形换位，逃跑成功率、神识与机缘极大提升。"},
    "鸿蒙炼体诀":   {"type": "防御", "grade": "玄级上品", "stat_bonus": {"physique": 4, "bone": 3}, "desc": "以鸿蒙混沌之力炼体，体魄与根骨得到恐怖强化。"},
    "三千雷动":     {"type": "攻击", "grade": "玄级上品", "stat_bonus": {"physique": 3, "soul": 3}, "desc": "以三千雷动之势出手，每一击都附带雷霆之威，体魄与神识同步大增。"},
    "狗刨轻功":     {"type": "辅助", "grade": "黄级下品", "stat_bonus": {"escape_rate": 3}, "desc": "模仿狗刨乱游的轻功，姿势难看但偶尔能多游出几丈，逃跑成功率略有提升。"},
    "歪风剑法":     {"type": "攻击", "grade": "黄级下品", "stat_bonus": {"physique": 1}, "desc": "招式歪歪扭扭的剑法，威力有限，仅能略微强化体魄。"},
    "散修打熬拳":   {"type": "攻击", "grade": "黄级下品", "stat_bonus": {"physique": 1}, "desc": "市井散修流行的打熬拳路，只能勉强锻炼肉身。"},
    "粗浅吐纳术":   {"type": "修炼", "grade": "黄级下品", "stat_bonus": {"cultivation_speed": 0.02}, "desc": "最基础的吐纳方法，修炼速度极其有限。"},
    "村野拳路":     {"type": "攻击", "grade": "黄级下品", "stat_bonus": {}, "desc": "乡间流传的拳路，几乎没有加成，只是比赤手空拳略强一点。"},
    "皮糙肉厚诀":   {"type": "防御", "grade": "黄级下品", "stat_bonus": {"physique": 1}, "desc": "让皮肉稍微结实一点的粗糙功法，体魄略有提升。"},
    "随便挥刀":     {"type": "攻击", "grade": "黄级下品", "stat_bonus": {}, "desc": "完全凭本能乱挥的刀法，不比普通凡人强多少。"},
    "歪门邪步":     {"type": "辅助", "grade": "黄级下品", "stat_bonus": {"escape_rate": 2}, "desc": "步伐古怪的身法，偶尔能让对手看花眼，逃跑成功率略有增加。"},
    "半吊子心法":   {"type": "修炼", "grade": "黄级下品", "stat_bonus": {"cultivation_speed": 0.015}, "desc": "只学了一半就失传的心法，修炼速度提升微乎其微。"},
    "乱星步":       {"type": "辅助", "grade": "黄级下品", "stat_bonus": {"escape_rate": 4}, "desc": "脚步乱如星散的身法，有时能躲开一两招。"},
    "破铜拳":       {"type": "攻击", "grade": "黄级下品", "stat_bonus": {}, "desc": "只能勉强打凹破铜烂铁的拳法，对强者几乎没有效果。"},
    "草莽刀法":     {"type": "攻击", "grade": "黄级下品", "stat_bonus": {"physique": 1}, "desc": "草莽之间互相砍伐演化出的刀法，只能略微强化体魄。"},
    "夜行小步":     {"type": "辅助", "grade": "黄级下品", "stat_bonus": {"escape_rate": 3}, "desc": "在夜里行走时不易被发现的步法，逃跑时略有帮助。"},
    "粗胚锻骨术":   {"type": "防御", "grade": "黄级下品", "stat_bonus": {"bone": 1}, "desc": "最粗糙的锻骨法门，只能略微增强根骨。"},
    "三脚猫剑":     {"type": "攻击", "grade": "黄级下品", "stat_bonus": {}, "desc": "三脚猫水平的剑法，只能对付比自己更菜的对手。"},
    "半桶水心法":   {"type": "修炼", "grade": "黄级下品", "stat_bonus": {"cultivation_speed": 0.01}, "desc": "似懂非懂乱修出来的心法，修炼速度提升可以忽略不计。"},
    "胡乱劈掌":     {"type": "攻击", "grade": "黄级下品", "stat_bonus": {}, "desc": "没有章法的乱掌，纯靠力气吃饭。"},
    "初级静坐术":   {"type": "修炼", "grade": "黄级下品", "stat_bonus": {"soul": 1}, "desc": "只教人如何打坐不睡着的入门术，神识略有提升。"},
    "勉强闪避术":   {"type": "辅助", "grade": "黄级下品", "stat_bonus": {"escape_rate": 3}, "desc": "勉强能让你多躲开一两招的躲闪术，效果有限。"},
    "糊涂悟道篇":   {"type": "修炼", "grade": "黄级下品", "stat_bonus": {"comprehension": 1}, "desc": "文理不通的悟道笔记，悟性略有提升。"},
    "粗糙护体气":   {"type": "防御", "grade": "黄级下品", "stat_bonus": {"physique": 1}, "desc": "勉强能挡一两招的护体气，体魄略有强化。"},
    "三流武馆拳":   {"type": "攻击", "grade": "黄级下品", "stat_bonus": {}, "desc": "三流武馆流行的拳法，只适合吓唬普通人。"},
    "旧版聚气术":   {"type": "修炼", "grade": "黄级下品", "stat_bonus": {"cultivation_speed": 0.02}, "desc": "过时的聚气术，只能略微提升修炼速度。"},
    "蹩脚腿法":     {"type": "攻击", "grade": "黄级下品", "stat_bonus": {}, "desc": "动作僵硬的腿法，很难真正踢中要害。"},
    "山寨金钟罩":   {"type": "防御", "grade": "黄级下品", "stat_bonus": {"physique": 1}, "desc": "仿制金钟罩的粗糙版本，只能略微增强防御。"},
    "业余采气诀":   {"type": "修炼", "grade": "黄级下品", "stat_bonus": {"cultivation_speed": 0.015}, "desc": "随便拼凑出来的采气心法，修炼效率堪忧。"},
    "落魄身法":     {"type": "辅助", "grade": "黄级下品", "stat_bonus": {"escape_rate": 4}, "desc": "落魄江湖客常用的身法，只能勉强提高一点逃跑成功率。"},
    "小巷偷袭术":   {"type": "攻击", "grade": "黄级下品", "stat_bonus": {"fortune": 1}, "desc": "适合在小巷偷袭的下三滥招数，偶尔能提高一点机缘。"},
    "半旧驭剑术":   {"type": "攻击", "grade": "黄级下品", "stat_bonus": {"comprehension": 1}, "desc": "残缺的驭剑术，只能略微提升悟性与御剑手感。"},
    "迟缓运功诀":   {"type": "修炼", "grade": "黄级下品", "stat_bonus": {"cultivation_speed": 0.01}, "desc": "运功极其缓慢的功法，修炼速度几乎看不出提升。"},
    "勉强御剑术":   {"type": "攻击", "grade": "黄级中品", "stat_bonus": {"comprehension": 1}, "desc": "勉强能把剑抬起来的御剑术，悟性略有提升。"},
    "粗制护盾术":   {"type": "防御", "grade": "黄级中品", "stat_bonus": {"physique": 1}, "desc": "护盾粗糙不堪，只能略微增强体魄防御。"},
    "小五行引气":   {"type": "修炼", "grade": "黄级中品", "stat_bonus": {"cultivation_speed": 0.05, "comprehension": 1}, "desc": "勉强涉及五行引气的入门心法，修炼速度与悟性略有提升。"},
    "普通养身诀":   {"type": "修炼", "grade": "黄级中品", "stat_bonus": {"lifespan_bonus": 4}, "desc": "普通人也能练的养身法门，寿元上限小幅提升。"},
    "市井游行步":   {"type": "辅助", "grade": "黄级中品", "stat_bonus": {"escape_rate": 6}, "desc": "市井游侠常用步伐，逃跑成功率略有提高。"},
    "练气村规拳":   {"type": "攻击", "grade": "黄级中品", "stat_bonus": {"physique": 1}, "desc": "某村自创的练气拳法，只能稍稍增强体魄。"},
    "粗浅辟毒法":   {"type": "辅助", "grade": "黄级中品", "stat_bonus": {"fortune": 1}, "desc": "粗糙的辟毒法门，运气好时或许能躲过一两次中毒。"},
    "简易收功诀":   {"type": "辅助", "grade": "黄级中品", "stat_bonus": {"soul": 1}, "desc": "收功用的简易心法，只能略微稳住神识。"},
    "常见静心咒":   {"type": "修炼", "grade": "黄级中品", "stat_bonus": {"soul": 1}, "desc": "坊间流行的静心咒，神识略有强化。"},
    "半成品战体":   {"type": "防御", "grade": "黄级中品", "stat_bonus": {"physique": 1, "bone": 1}, "desc": "只修成一半的战体功法，体魄与根骨均有小幅提升。"},
}

LEGENDARY_TECHNIQUES = {
    "大荒囚天指":   {"type": "攻击", "grade": "天级上品", "stat_bonus": {"physique": 8, "bone": 6, "soul": 4, "comprehension": 5}, "desc": "上古大荒遗留的禁忌指法，一指落下天地变色，据说修至圆满可囚禁天道本身。"},
    "诛仙剑阵":     {"type": "攻击", "grade": "天级上品", "stat_bonus": {"comprehension": 8, "soul": 6, "cultivation_speed": 0.80}, "desc": "上古四大凶阵之首，以四把诛仙剑布阵，阵成之日诸仙皆诛，悟性与神识极大强化。"},
    "混沌开天斩":   {"type": "攻击", "grade": "天级上品", "stat_bonus": {"physique": 6, "comprehension": 6, "bone": 5}, "desc": "以混沌之力重演开天辟地一斩，每一击都蕴含毁天灭地之威，三项属性恐怖强化。"},
    "灭世神拳":     {"type": "攻击", "grade": "天级中品", "stat_bonus": {"physique": 10, "bone": 4}, "desc": "以肉身之力毁灭一切的拳法，体魄强化程度令人发指，据说练至大成可一拳碎星。"},
    "万古噬魂爪":   {"type": "攻击", "grade": "天级中品", "stat_bonus": {"soul": 8, "fortune": 4, "bone": 3}, "desc": "以神识化爪撕裂对手元神，神识极大强化，被此爪击中者魂飞魄散。"},

    "太古洪荒经":   {"type": "修炼", "grade": "天级上品", "stat_bonus": {"cultivation_speed": 1.00, "comprehension": 6, "soul": 4, "bone": 3}, "desc": "太古时期流传下来的第一部修炼功法，修炼速度翻倍，四项属性全面强化，得之者无不飞升。"},
    "造化玉碟心法": {"type": "修炼", "grade": "天级上品", "stat_bonus": {"cultivation_speed": 0.80, "comprehension": 5, "fortune": 5, "lifespan_bonus": 50}, "desc": "造化玉碟所载的无上心法，修炼速度与机缘极大提升，寿元延长效果冠绝万古。"},
    "鸿蒙本源诀":   {"type": "修炼", "grade": "天级中品", "stat_bonus": {"cultivation_speed": 0.70, "comprehension": 4, "physique": 4, "soul": 4}, "desc": "以鸿蒙本源之气修炼，三维属性同步极大强化，修炼速度恐怖，传说修至圆满可窥见大道。"},

    "不灭金身":     {"type": "防御", "grade": "天级上品", "stat_bonus": {"physique": 10, "bone": 8, "soul": 3}, "desc": "佛门至高防御神通，肉身修至不灭之境，体魄与根骨强化程度令天地失色，几乎无法被击杀。"},

    "天道轮回步":   {"type": "辅助", "grade": "天级中品", "stat_bonus": {"escape_rate": 60, "fortune": 6, "soul": 4}, "desc": "以天道轮回之力驱动步法，逃跑成功率高到令人绝望，据说此步一出追者皆空。"},
    "因果业火咒":   {"type": "辅助", "grade": "天级下品", "stat_bonus": {"fortune": 8, "soul": 5, "comprehension": 3}, "desc": "以因果业力燃烧对手，机缘与神识极大强化，被此咒缠身者业障缠身难以修炼。"},
}

WORLD_TECHNIQUES = {**WORLD_TECHNIQUES, **LEGENDARY_TECHNIQUES}
