COMMON_QUESTS = [
    {
        "id": "c001",
        "title": "驱逐采花贼",
        "desc": "城郊近日出没一名采花贼，已有数名女修受害，茶馆悬赏捉拿。",
        "type": "combat",
        "req": {"min_realm": "炼气期1层"},
        "enemy": {"name": "采花贼", "power": 30},
        "rewards": {"spirit_stones": 800, "reputation": 10, "cultivation": 50},
    },
    {
        "id": "c002",
        "title": "剿灭山贼",
        "desc": "官道上的山贼劫掠商旅，商会出资悬赏，击退即可领赏。",
        "type": "combat",
        "req": {"min_realm": "炼气期3层"},
        "enemy": {"name": "山贼头目", "power": 60},
        "rewards": {"spirit_stones": 1500, "reputation": 15, "cultivation": 80},
    },
    {
        "id": "c003",
        "title": "采集灵草",
        "desc": "药铺急需百草谷的青心草，需前往百草谷采集10株。",
        "type": "gather",
        "req": {"min_realm": "炼气期1层"},
        "location": "百草谷",
        "rewards": {"spirit_stones": 600, "reputation": 8, "soul": 1},
    },
    {
        "id": "c004",
        "title": "挖取灵石矿",
        "desc": "漠北荒漠发现新矿脉，需前往开采一批地阶灵石。",
        "type": "gather",
        "req": {"min_realm": "炼气期3层"},
        "location": "漠北荒漠",
        "rewards": {"spirit_stones": 1200, "reputation": 10, "physique": 1},
    },
    {
        "id": "c005",
        "title": "护送商队",
        "desc": "一支商队需要护送至下一城市，途中可能遭遇劫匪。",
        "type": "combat",
        "req": {"min_realm": "炼气期5层"},
        "enemy": {"name": "劫匪", "power": 90},
        "rewards": {"spirit_stones": 2000, "reputation": 20, "cultivation": 100},
    },
    {
        "id": "c006",
        "title": "捕捉妖兽",
        "desc": "万妖岭边缘出现低阶妖兽扰民，需前往驱逐。",
        "type": "gather",
        "req": {"min_realm": "炼气期5层"},
        "location": "万妖岭",
        "rewards": {"spirit_stones": 1800, "reputation": 15, "bone": 1},
    },
]
