ELITE_QUESTS = [
    {
        "id": "e001",
        "title": "斩杀江洋大盗",
        "desc": "江湖上臭名昭著的「血手魔」流窜至此，官府悬赏极高，但此人修为不低。",
        "type": "combat",
        "req": {"min_realm": "筑基期1层"},
        "enemy": {"name": "血手魔", "power": 300},
        "rewards": {"spirit_stones": 5000, "reputation": 40, "cultivation": 300,
                    "technique": "金钟罩"},
    },
    {
        "id": "e002",
        "title": "深入古战场",
        "desc": "古战场深处发现一处封印，需要修士前往探查并带回残留的功法碎简。",
        "type": "gather",
        "req": {"min_realm": "筑基期3层", "min_stat": {"comprehension": 7}},
        "location": "古战场",
        "rewards": {"spirit_stones": 4000, "reputation": 35, "comprehension": 1,
                    "technique": "穿云剑法"},
    },
    {
        "id": "e003",
        "title": "寒玉窟探险",
        "desc": "寒玉窟深处有一批万年寒玉，但守护的冰系妖兽极为凶猛。",
        "type": "gather",
        "req": {"min_realm": "筑基期5层", "min_stat": {"physique": 7}},
        "location": "寒玉窟",
        "rewards": {"spirit_stones": 6000, "reputation": 45, "physique": 1,
                    "technique": "罡气护体"},
    },
    {
        "id": "e004",
        "title": "剿灭邪修据点",
        "desc": "一伙邪修在城郊建立据点，为祸一方，宗门联合悬赏清剿。",
        "type": "combat",
        "req": {"min_realm": "筑基期5层", "min_stat": {"soul": 7}},
        "enemy": {"name": "邪修首领", "power": 500},
        "rewards": {"spirit_stones": 7000, "reputation": 50, "soul": 1,
                    "technique": "万象归一"},
    },
    {
        "id": "e005",
        "title": "幽冥海采珠",
        "desc": "幽冥海深处的灵珠是炼制高阶丹药的关键材料，价值连城。",
        "type": "gather",
        "req": {"min_realm": "筑基期7层"},
        "location": "幽冥海",
        "rewards": {"spirit_stones": 8000, "reputation": 55, "lifespan": 10,
                    "technique": "神行百变"},
    },
]
