LEGENDARY_QUESTS = [
    {
        "id": "l001",
        "title": "昆仑秘境·封印守护者",
        "desc": "昆仑秘境深处的上古封印出现裂缝，一头远古凶兽即将破封而出，需强者前往镇压。",
        "type": "combat",
        "req": {"min_realm": "结丹期初期", "min_stat": {"comprehension": 8, "physique": 8}},
        "enemy": {"name": "远古凶兽", "power": 2000},
        "rewards": {"spirit_stones": 20000, "reputation": 150, "lifespan": 30,
                    "technique": "混元一气功", "stat_bonus": {"comprehension": 2}},
    },
    {
        "id": "l002",
        "title": "虚空裂缝·时空乱流",
        "desc": "虚空裂缝中出现时空乱流，上古传承随之浮现，只有最强者才能取走。",
        "type": "combat",
        "req": {"min_realm": "元婴期初期"},
        "enemy": {"name": "时空傀儡", "power": 8000},
        "rewards": {"spirit_stones": 50000, "reputation": 300, "lifespan": 100,
                    "technique": "逍遥游", "stat_bonus": {"soul": 3, "comprehension": 2}},
    },
    {
        "id": "l003",
        "title": "天雷谷·渡劫试炼",
        "desc": "天雷谷中有一道上古雷劫试炼，通过者可获得雷属天道感悟，修为大进。",
        "type": "gather",
        "req": {"min_realm": "结丹期中期", "min_stat": {"bone": 8}},
        "location": "天雷谷",
        "rewards": {"spirit_stones": 15000, "reputation": 120, "cultivation": 2000,
                    "technique": "九转玄功", "stat_bonus": {"bone": 2}},
    },
    {
        "id": "l004",
        "title": "万妖岭·妖王讨伐",
        "desc": "万妖岭深处的妖王苏醒，率领妖兽大军威胁周边城市，各大宗门联合悬赏。",
        "type": "combat",
        "req": {"min_realm": "结丹期后期", "min_stat": {"physique": 9}},
        "enemy": {"name": "万妖岭妖王", "power": 5000},
        "rewards": {"spirit_stones": 30000, "reputation": 200, "lifespan": 50,
                    "technique": "万剑归宗", "stat_bonus": {"physique": 2, "bone": 1}},
    },
]
